
CREATE TABLE CustomerFavoriteProperty (
                                          customer_id varchar(100) NOT NULL,
                                          property_id varchar(100) NOT NULL,
                                          created_at  timestamp DEFAULT CURRENT_TIMESTAMP,
                                          updated_at  timestamp DEFAULT CURRENT_TIMESTAMP,
                                          PRIMARY KEY (customer_id,
                                                       property_id));
CREATE TABLE CustomerPreferredPropertyType (
                                               customer_id      varchar(100) NOT NULL,
                                               property_type_id varchar(100) NOT NULL,
                                               created_at       timestamp DEFAULT CURRENT_TIMESTAMP,
                                               updated_at       timestamp DEFAULT CURRENT_TIMESTAMP,
                                               PRIMARY KEY (customer_id,
                                                            property_type_id));
CREATE TABLE CustomerPreferredWard (
                                       customer_id varchar(100) NOT NULL,
                                       ward_id     varchar(100) NOT NULL,
                                       created_at  timestamp DEFAULT CURRENT_TIMESTAMP,
                                       updated_at  timestamp DEFAULT CURRENT_TIMESTAMP,
                                       PRIMARY KEY (customer_id,
                                                    ward_id));

CREATE TABLE Report (
                        report_id    varchar(100) NOT NULL,
                        report_type  varchar(255) NOT NULL,
                        report_month int4,
                        report_year  int4,
                        title        varchar(200) NOT NULL,
                        description  text,
                        start_date   date NOT NULL,
                        end_date     date NOT NULL,
                        file_path    varchar(500),
                        file_format  varchar(255) NOT NULL,
                        status       varchar(255) DEFAULT 'Generating',
                        completed_at timestamp,
                        created_at   timestamp DEFAULT CURRENT_TIMESTAMP,
                        updated_at   timestamp DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY (report_id));
CREATE TABLE FinancialReport (
                                 report_id                             varchar(100) NOT NULL,
                                 total_revenue_current_month           numeric(15, 2),
                                 total_revenue                         numeric(15, 2),
                                 total_service_fees_current_month      numeric(15, 2),
                                 total_service_fees                    numeric(15, 2),
                                 contract_count_current_month          int4,
                                 contract_count                        int4,
                                 total_commission_earned_current_month numeric(15, 2),
                                 total_commission_earned               numeric(15, 2),
                                 top_performing_city_id                varchar(100) NOT NULL,
                                 top_performing_district_id            varchar(100) NOT NULL,
                                 top_performing_ward_id                varchar(100),
                                 top_performing_property_type_id       varchar(100),
                                 net_profit                            numeric(15, 2),
                                 avg_property_price                    numeric(15, 2),
                                 total_rates                           int4,
                                 avg_rating                            numeric(5, 2),
                                 total_rates_current_month             int4,
                                 avg_rating_current_month              numeric(5, 2),
                                 created_at                            timestamp DEFAULT CURRENT_TIMESTAMP,
                                 updated_at                            timestamp DEFAULT CURRENT_TIMESTAMP,
                                 PRIMARY KEY (report_id));
CREATE TABLE AgentPerformanceReport (
                                        report_id                               varchar(100) NOT NULL,
                                        "total_ agents"                         int4,
                                        total_active_agents                     int4,
                                        top_performer_agent_id_current_month    varchar(100) NOT NULL,
                                        top_performer_revenue_current_month     numeric(15, 2) DEFAULT TRUE,
                                        top_performer_agent_id                  varchar(100) NOT NULL,
                                        top_performer_revenue                   numeric(15, 2) DEFAULT CURRENT_TIMESTAMP,
                                        bottom_performer_agent_id_current_month varchar(100) NOT NULL,
                                        bottom_performer_revenue_current_month  numeric(15, 2),
                                        avg_revenue_per_agent                   numeric(15, 2),
                                        avg_customer_satisfaction               int4,
                                        total_rates                             int4,
                                        avg_rating                              numeric(5, 2),
                                        total_rates_current_month               int4,
                                        avg_rating_current_month                numeric(5, 2),
                                        created_at                              timestamp,
                                        updated_at                              timestamp DEFAULT CURRENT_TIMESTAMP,
                                        PRIMARY KEY (report_id));
CREATE TABLE PropertyStatisticsReport (
                                          report_id                             varchar(100) NOT NULL,
                                          total_active_properties               int4,
                                          total_sold_properties_current_month   int4,
                                          total_sold_properties                 numeric(5, 2) DEFAULT TRUE,
                                          total_rented_properties_current_month numeric(15, 2),
                                          total_rented_properties               int4,
                                          most_popular_property_type_id         varchar(255),
                                          most_popular_location_id              varchar(255),
                                          created_at                            timestamp DEFAULT CURRENT_TIMESTAMP,
                                          updated_at                            timestamp DEFAULT CURRENT_TIMESTAMP,
                                          PRIMARY KEY (report_id));
CREATE TABLE CustomerAnalyticsReport (
                                         report_id                            varchar(100) NOT NULL,
                                         total_active_customers               int4 DEFAULT 'All',
                                         new_customers_acquired_current_month int4 DEFAULT 'All',
                                         customer_churn_rate                  numeric(5, 2),
                                         avg_customer_transaction_value       numeric(15, 2),
                                         high_value_customers_count           int4 DEFAULT TRUE,
                                         customer_satisfaction_score          numeric(5, 2) DEFAULT TRUE,
                                         total_rates                          int4,
                                         avg_rating                           numeric(5, 2),
                                         total_rates_current_month            int4,
                                         avg_rating_current_month             numeric(5, 2),
                                         created_at                           timestamp DEFAULT CURRENT_TIMESTAMP,
                                         updated_at                           timestamp DEFAULT CURRENT_TIMESTAMP,
                                         PRIMARY KEY (report_id));
CREATE TABLE ViolationReportDetails (
                                        report_id                               varchar(100) NOT NULL,
                                        total_violations_reported               int4 DEFAULT 'All',
                                        total_violations_reported_current_month int4 DEFAULT 'All',
                                        serious_violations_count_curent_month   int4 DEFAULT 'All',
                                        serious_violations_count                int4 DEFAULT 'All',
                                        minor_violations_count_curent_month     int4 DEFAULT TRUE,
                                        minor_violations_count                  int4 DEFAULT TRUE,
                                        avg_resolution_time_hours               int4 DEFAULT TRUE,
                                        violation_trend                         numeric(5, 2),
                                        most_common_violation_type              varchar(255),
                                        accounts_suspended                      int4,
                                        compliance_rate                         numeric(5, 2),
                                        created_at                              timestamp DEFAULT CURRENT_TIMESTAMP,
                                        updated_at                              timestamp DEFAULT CURRENT_TIMESTAMP,
                                        PRIMARY KEY (report_id));
CREATE TABLE IndividualSalesAgentRanking (
                                             ranking_id                      varchar(255) NOT NULL,
                                             agent_id                        varchar(100) NOT NULL,
                                             ranking_month                   int4,
                                             ranking_year                    int4,
                                             month_revenue                   numeric(15, 2),
                                             month_deals                     int4,
                                             month_properties_assigned       int4,
                                             month_appointments_completed    int4,
                                             month_customer_satisfaction_avg numeric(3, 2),
                                             performance_tier                varchar(255),
                                             ranking_position                int4,
                                             created_at                      timestamp,
                                             updated_at                      timestamp,
                                             PRIMARY KEY (ranking_id));
CREATE TABLE IndividualCustomerLead (
                                        lead_id                  varchar(255) NOT NULL,
                                        customer_id              varchar(100) NOT NULL,
                                        lead_month               int4,
                                        lead_year                int4,
                                        month_viewings_requested int4,
                                        month_viewings_attended  int4,
                                        month_spending           numeric(15, 2),
                                        month_purchases          numeric(15, 2),
                                        month_rentals            numeric(15, 2),
                                        month_contracts_signed   int4,
                                        lead_score               int4,
                                        lead_classification      varchar(255),
                                        customer_tier            varchar(255),
                                        created_at               timestamp,
                                        updated_at               timestamp,
                                        PRIMARY KEY (lead_id));

CREATE TABLE CustomerPreferredDistrict (
                                           customer_id varchar(100) NOT NULL,
                                           district_id varchar(100) NOT NULL,
                                           created_at  timestamp,
                                           updated_at  timestamp,
                                           PRIMARY KEY (customer_id,
                                                        district_id));
CREATE TABLE CustomerPreferredCity (
                                       customer_id varchar(100) NOT NULL,
                                       city_id     varchar(100) NOT NULL,
                                       created_at  timestamp,
                                       updated_at  timestamp,
                                       PRIMARY KEY (customer_id,
                                                    city_id));